travis:
  secure:
    BINSTAR_TOKEN: Tqs/VYif8h1KGi90ELNNN3Osbkk3EulDk8O+1jstMqHTBLb+RrqXRwxvnqbwfD4ihx4u3Ep8vAEgZOmOuBAMMTkBxXLJhQIIxMpfCXazZ6VOTpVhkYEjZoRJmPL4y1ctfXbHHtGUI6WEDKxZq0PSTiQ282YWMkfRTxbPxyAjsdMLDRIgSwv1HB69CA2ANoyTMgbf9v3nbcVVy2FjskkPxesxyZM8XpgPVC4RbBR+S+zWaLbuu3ZjDM7BgCKr+mr+9KMXYNC0gfRqd8NEB9DaGO0p9sTPouCWgJ/5CsBOySHAC/YKl5HvsWrhhPt0F94H4hI+4uj9fi4OuKXKNz8W7SALCscGr8T1e5m5NCHK6FqAldaYjlV+uZYWVNyrDjmL5Op8nQG8iuarIBNJ3wy2oE9G9T7T/hUBuO9Qrgsgkaq19osPEhravrmXYoPb+4hqKsVIjKG0EAbFuD+l30G7FLK0ZQB43avDclH6xlsAqmGwDLvKE1siPscMo99MYlNIf4R+epLZIm3/XugvY1S5Zg5nQ4mg0zbJtr16kWLy74vbr0krHg04hqP6wNEBtanmZmgf+Wqyy4b8+BXU0FR8mM2A/p9dfBs2NLgF8X+PUScPpAdASs62N441QIO7XZV8SWqmuP2njbJaV9yznt33YeXzY6BpkeVKQGmalMh76jw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
